### ISSUE TITLE
import MySQLdb 问题

### ISSUE THREAD

**Issue by weiyi88** [zcyuefan/zentao_reporter#1]
这python是版本几？
我用python3.8、python3.10，都遇到

Traceback (most recent call last):
  File "/Users/Aring/Desktop/Project/Python/zentao_reporter/zentao_reporter.py", line 11, in <module>
    import MySQLdb
  File "/Users/Aring/opt/anaconda3/envs/HelpJob/lib/python3.10/site-packages/MySQLdb/__init__.py", line 17, in <module>
    from . import _mysql
ImportError: dlopen(/Users/Aring/opt/anaconda3/envs/HelpJob/lib/python3.10/site-packages/MySQLdb/_mysql.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'

这个问题，但是不知道怎么解决，请大神指教

**Comment by weiyi88** [comment]
应该不是python版本问题，我使用2.7版本，也会有该情况。不过，本人电脑是，mac air m1 ，不知道是否与电脑环境相关


  File "zentao_reporter.py", line 11, in <module>
    import MySQLdb
  File "/Users/Aring/opt/anaconda3/envs/jobjob/lib/python2.7/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/Aring/opt/anaconda3/envs/jobjob/lib/python2.7/site-packages/MySQLdb/_mysql.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'
